---
- name: Installation et configuration d'OpenSSH avec bannière de sécurité
  hosts: linux
  become: yes

  tasks:
    - name: Installer OpenSSH server
      apt:
        name: openssh-server
        state: present
        update_cache: yes

    - name: Configurer SSH pour utiliser uniquement le protocole SSHv2
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Protocol'
        line: 'Protocol 2'
        state: present

    - name: Créer la bannière SSH
      copy:
        dest: /etc/ssh/banner
        content: |
          ********************************************************
          *                 AVERTISSEMENT                        *
          ********************************************************
          *  Cette connexion est la propriété de la société X.   *
          *  L'accès est autorisé uniquement aux utilisateurs    *
          *  autorisés. Toute autre tentative constitue une      *
          *  violation de la sécurité et sera poursuivie en      *
          *  justice.                                            *
          ********************************************************
          ********************************************************
          *                    WARNING                           *
          ********************************************************
          *  This connection is the property of X. Access is     *
          *  only permitted to authorized users. Any other       *
          *  access attempt constitutes a violation of system    *
          *  security and will be prosecuted to the fullest      *
          *  extent of the law.                                  *
          ********************************************************

    - name: Activer la bannière dans la configuration SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Banner'
        line: 'Banner /etc/ssh/banner'
        state: present

    - name: Vérifier la syntaxe de la configuration SSH
      command: sshd -t
      register: ssh_syntax_check
      ignore_errors: yes

    - name: Valider la configuration SSH
      fail:
        msg: "Erreur de syntaxe dans /etc/ssh/sshd_config. Veuillez vérifier et corriger."
      when: ssh_syntax_check.rc != 0

  handlers:
    - name: Redémarrer le service SSH
      service:
        name: sshd
        state: restarted
