---
- name: Désactivation de la connexion root via SSH
  hosts: linux
  become: yes
  vars_files:
    - vault/credentials.yml
  tasks:
    - name: Vérifier si le fichier de configuration SSH existe
      stat:
        path: /etc/ssh/sshd_config
      register: ssh_config

    - name: Avertir si le fichier de configuration SSH est introuvable
      debug:
        msg: "Le fichier de configuration /etc/ssh/sshd_config est introuvable."
      when: not ssh_config.stat.exists
      failed_when: not ssh_config.stat.exists

    - name: Désactiver la connexion root via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
      notify:
        - Restart SSH service

  handlers:
    - name: Restart SSH service
      systemd:
        name: ssh
        state: restarted
        enabled: yes
