---
- name: Installer et configurer Fail2Ban sur les machines Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Mettre à jour les paquets
      apt:
        update_cache: yes

    - name: Installer Fail2Ban et iptables
      apt:
        name:
          - fail2ban
          - iptables
        state: present
        update_cache: yes

    - name: Copier le fichier de configuration Fail2Ban (jail.conf -> jail.local)
      copy:
        remote_src: yes
        src: /etc/fail2ban/jail.conf
        dest: /etc/fail2ban/jail.local
        force: no  # Ne pas écraser si le fichier existe déjà

    - name: Modifier le backend de Fail2Ban pour utiliser systemd
      lineinfile:
        path: /etc/fail2ban/jail.local
        regexp: '^backend = .*'
        line: 'backend = systemd'

    - name: Redémarrer le service Fail2Ban
      systemd:
        name: fail2ban
        state: restarted
        enabled: yes

    - name: Vérifier le statut du service Fail2Ban
      shell: systemctl status fail2ban.service
      register: fail2ban_status
      changed_when: false

    - name: Afficher le statut du service Fail2Ban
      debug:
        var: fail2ban_status.stdout_lines

    - name: Vérifier le statut de la jail SSHD
      shell: fail2ban-client status sshd
      register: fail2ban_client_status
      changed_when: false

    - name: Afficher le statut de la jail SSHD
      debug:
        var: fail2ban_client_status.stdout_lines
