---
- name: Correctif de sécurité | Mise à jour paquet | Unattended-upgrade | Forwarding
  hosts: linux
  vars_files:
    - vault/credentials.yml
  become: True
  tasks:

##SSHv2
    - name: Ensure only SSH Protocol 2 is allowed
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^Protocol'
        line: 'Protocol 2'
      notify:
        - Restart SSH Service


##Mise à jour des paquets & configuration de unattended-upgrades
    - name: Mettre à jour la cache des paquets et les paquets
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
        force_apt_get: yes

    - name: S'assurer que unattended-upgrades est installé
      apt:
        name: unattended-upgrades
        state: present

    - name: Activer et configurer les mises à jour automatiques du fichier 20auto-upgrades
      template:
        src: /etc/apt/apt.conf.d/20auto-upgrades
        dest: /etc/apt/apt.conf.d/20auto-upgrades


    - name: Activer et configurer les mises à jour automatiques du fichier 50unattended-upgrades
      copy:
        src: /etc/apt/apt.conf.d/50unattended-upgrades
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
      notify: Redémarrer unattended-upgrades


    - name: Installer les correctifs de sécurité
      apt:
        name:
        - linux-generic
        - linux-image-generic
        state: latest
        update_cache: yes


##Redirection de flux
    - name: Désactiver IP forwarding pour IPv4
      sysctl:
        name: net.ipv4.ip_forward
        value: '0'
        state: present
        reload: yes

    - name: Désactiver IP forwarding pour IPv6
      sysctl:
        name: net.ipv6.conf.all.forwarding
        value: '0'
        state: present
        reload: yes

    - name: Assurer que les changements sont persistants après redémarrage pour IPv4
      lineinfile:
        path: /etc/sysctl.conf
        regexp: '^net.ipv4.ip_forward'
        line: 'net.ipv4.ip_forward = 0'
        state: present

    - name: Assurer que les changements sont persistants après redémarrage pour IPv6
      lineinfile:
        path: /etc/sysctl.conf
        regexp: '^net.ipv6.conf.all.forwarding'
        line: 'net.ipv6.conf.all.forwarding = 0'
        state: present

    - name: Recharger la configuration sysctl
      command: sysctl -p
      args:
        warn: no


  handlers:

    - name: Redémarrer unattended-upgrades
      systemd:
        name: unattended-upgrades
        state: restarted