---
- name: Configurer la sécurité des serveurs Linux
  hosts: linux
  become: yes
  vars_files:
    - vault/credentials.yml

  tasks:
    # --- Section 1 : Désactivation de la connexion root via SSH ---
    - name: Vérifier si le fichier de configuration SSH existe
      stat:
        path: /etc/ssh/sshd_config
      register: ssh_config

    - name: Avertir si le fichier de configuration SSH est introuvable
      debug:
        msg: "Le fichier de configuration /etc/ssh/sshd_config est introuvable."
      when: not ssh_config.stat.exists
      failed_when: not ssh_config.stat.exists

    - name: Désactiver la connexion root via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
      notify:
        - Restart SSH service

    # --- Section 2 : Installation et configuration de Fail2Ban ---
    - name: Mettre à jour les paquets
      apt:
        update_cache: yes

    - name: Installer Fail2Ban et iptables
      apt:
        name:
          - fail2ban
          - iptables
        state: present
        update_cache: yes

    - name: Copier le fichier de configuration Fail2Ban (jail.conf -> jail.local)
      copy:
        remote_src: yes
        src: /etc/fail2ban/jail.conf
        dest: /etc/fail2ban/jail.local
        force: no  # Ne pas écraser si le fichier existe déjà

    - name: Modifier le backend de Fail2Ban pour utiliser systemd
      lineinfile:
        path: /etc/fail2ban/jail.local
        regexp: '^backend = .*'
        line: 'backend = systemd'

    - name: Redémarrer le service Fail2Ban
      systemd:
        name: fail2ban
        state: restarted
        enabled: yes

    - name: Vérifier le statut du service Fail2Ban
      shell: systemctl status fail2ban.service
      register: fail2ban_status
      changed_when: false

    - name: Afficher le statut du service Fail2Ban
      debug:
        var: fail2ban_status.stdout_lines

    - name: Vérifier le statut de la jail SSHD
      shell: fail2ban-client status sshd
      register: fail2ban_client_status
      changed_when: false

    - name: Afficher le statut de la jail SSHD
      debug:
        var: fail2ban_client_status.stdout_lines

  handlers:
    - name: Restart SSH service
      systemd:
        name: ssh
        state: restarted
        enabled: yes
