name: CI Pipeline

on: [push]

jobs:
  deploy-ansible:
    runs-on: self-hosted

    steps:

    - name: ping
      run: ansible-playbook -i /home/ansible/devops-project/hosts /home/ansible/devops-project/ping.yml --ask-vault-pass
