name: CI Pipeline

on: [push]

jobs:
  deploy-ansible:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts

    - name: ping
      run: ssh -i ~/.ssh/id_rsa ansible@192.168.1.200 "ls /home/ansible"

#test