name: CI Pipeline

on: [push]

jobs:
  deploy-ansible:
    runs-on: self-hosted

    steps:

    - name: création fichier vault password
      run: echo "${{ secrets.Vault }}" > /home/ansible/devops-project/vault_password.txt

    - name: playbook ping
      run: ansible-playbook -i /home/ansible/devops-project/hosts /home/ansible/devops-project/ping.yml --vault-password-file /home/ansible/devops-project/vault_password.txt
