name: CI Pipeline

on: [push]

jobs:
  deploy-ansible:
    runs-on: ubuntu-latest

    steps:
    - name: ping
      run: ansible-playbook -i /home/ansible/devops-project/hosts /home/ansible/devops-project/test.yml --ask-vault-pass
